# Purpose: Take the DomainUserProfiles.CSV generated by
# getUserListAsCSV.ps1 and determine if users are disabled
# Created By: Cory Laidlaw

# Input CSV path, CSV generated by getUserListAsCSV.ps1
$csvPath = "C:\Temp\DomainUserProfiles.csv"

# Import CSV
$users = Import-Csv -Path $csvPath

# Initialize list to collect disabled users
$disabledUsers = @()

# Loop through each user in the CSV
foreach ($user in $users) {
    $samAccountName = $user.Username
    $domain = $user.Domain

    # Try to get the AD user
    $adUser = Get-ADUser -Filter { SamAccountName -eq $samAccountName } -Properties DistinguishedName -ErrorAction SilentlyContinue

    # For AD users, check if Enabled or Disabled
    if ($null -ne $adUser) {
        $ou = ($adUser.DistinguishedName -split ",", 2)[1]
        if (-not $adUser.Enabled) {
            if ($ou -notlike "*OU=Disabled Users,*") { 
                #Output user's OU if Disabled and not in Disabled Users
                Write-Output "User $samAccountName is DISABLED. OU: $ou" 
            } else {
                Write-Output "User $samAccountName is DISABLED."
            }
            $disabledUsers += $user
        } else {
            Write-Output "User $samAccountName is ENABLED."
        }
    } else {
        Write-Output "User $samAccountName could not be found in AD. Adding to Disabled Users list."
        $disabledUsers += $user
    }
}

# Export disabled users to CSV C:\Temp\DisabledUsers.csv
$disabledUsers | Export-Csv -Path "C:\Temp\DisabledUsers.csv" -NoTypeInformation
