# Purpose: Remove Old User Profiles
# Created by: Cory Laidlaw

# Import CSV Generated by GetUserListAsCSV.ps1 or checkCSVListForDisabledUsers.ps1
$CsvPath = "C:\Temp\DisabledUsers.csv"

# Import the CSV file
$UserProfiles = Import-Csv -Path $CsvPath

# Deletes each user from the PC
foreach ($User in $UserProfiles) {
    $ProfilePath = $User.Profilepath
    $Username = $User.Username

    # Output to keep track of progress
    Write-Output "Attempting to remove profile for user: $Username at path: $ProfilePath"

    # Remove user profile
    Get-WmiObject Win32_UserProfile |
        Where-Object { $_.LocalPath -eq $ProfilePath } |
        ForEach-Object {
            $_.Delete()
            Write-Output "Profile for $Username removed successfully."
        }
}

# Display free space on C drive
$drive = Get-PSDrive C; "Free: $([math]::Round($drive.Free / 1GB, 2)) GB ($([math]::Round(($drive.Free / ($drive.Used + $drive.Free)) * 100, 2))%)"
